--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: commonpasswordservice
  name: commonpasswordservice-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: commonpasswordservice
  template: 
    metadata: 
      labels: 
        app: commonpasswordservice
    spec: 
      containers: 
          - image: sachinmahanin/commonpassword:latest
            name: commonpassword
            ports: 
              - containerPort: 18607
                protocol: TCP
            env:
              - name: PASSWORD_URL
                valueFrom:
                  configMapKeyRef:
                    name: commonpassword-configmap
                    key: PASSWORD_URL    
              - name: PASSWORD_PATH
                valueFrom:
                  configMapKeyRef:
                    name: commonpassword-configmap
                    key: PASSWORD_PATH
